<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Форма</title>
</head>
<body>
<form action="">
    <fieldset>
        <label for="email">E-mail</label>
        <input type="email" name="email" id="email">

        <label for="age">Возраст</label>
        <input type="number" name="age" id="age">

        <label for="password">Пароль</label>
        <input type="password" name="password" id="password">

        <label for="password_confirm">Повторите пароль</label>
        <input type="password" name="password_confirm" id="password_confirm">

        <button type="submit">Зарегистрироваться</button>
    </fieldset>
</form>
</body>
</html>