<?php session_start() ?>
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">

    <title>Подтвердите свой возраст</title>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-lg-9 mx-auto my-5">
            <h1 class="text-center mb-5">
                Подтвердите свой возраст!
            </h1>

            <?php if (isset($_SESSION['errors'])): ?>
                <div class="alert alert-danger" role="alert">
                    <?php foreach ($_SESSION['errors'] as $key => $error): ?>
                        <p><?php echo $error['message']; ?></p>
                    <?php endforeach ?>
                </div>
            <?php endif ?>

            <form action="controller.php" method="post" class="form-inline justify-content-center">
                <div class="form-group mr-2">
                    <input type="number" name="year" min="1900" max="2020" class="form-control" placeholder="Год">
                </div>
                <div class="form-group mr-2">
                    <input type="number" name="month" min="1" max="12" class="form-control" placeholder="Месяц">
                </div>
                <div class="form-group mr-2">
                    <input type="number" name="day" min="1" max="31" class="form-control" placeholder="День">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        Мне 18!
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>